name: Daily process (crash reports, update translations)
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 23 * * *"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: install netlify-ctl
        run: npm install -g netlify-cli

      - name: Check out source code
        uses: actions/checkout@v2

      - name: process craches and netfliy deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          SPACES_KEY: ${{ secrets.SPACES_KEY }}
          SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
        run: .\doit.bat -crashes

      - name: update translations
        env:
          TRANS_UPLOAD_SECRET: ${{ secrets.TRANS_UPLOAD_SECRET }}
        run: .\doit.bat -ci-trans-update
